### ISSUE TITLE
Adding new Visuals / Improving an existing one

### ISSUE THREAD

**Issue by jyotirmoy-paul** [creepymaniac/Visualize-Tower_of_Hanoi#1]
# Adding new Visuals
* Anything that's fun to visualize, related to any topic
* Visualization of any algorithm, or physics phenomenon, or whatever!

# Improving an existing Visuals
* You can suggest a better way of doing something
* Or might be, a better algorithm

## I would appreciate your help if you could contribute anything that's fun & cool to visualize. I'm also open to any suggestions/ideas regarding any topics that can be visualized.

Guess @anishk74 you could help?

**Comment by anishk74** [comment]
Yeah would love to add something here

**Comment by jyotirmoy-paul** [comment]
@anishk74 For JavaScript lovers like you, there's p5.js, have a look [here](https://p5js.org/get-started/)
I'm looking forward to see what interesting thing you gonna built.
